services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        SC_PYTHON_VERSION: ${SC_PYTHON_VERSION:-3.13}
    volumes:
      - .:/app
      - ~/.ipython:/root/.ipython
      - ~/.cache:/root/.cache
      - /usr/local/lib/protobuf/include/hedwig:/usr/local/lib/protobuf/include/hedwig
