# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='schema.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cschema.proto\" \n\rUserCreatedV1\x12\x0f\n\x07user_id\x18\x01 \x01(\t\" \n\rUserUpdatedV1\x12\x0f\n\x07user_id\x18\x01 \x01(\tb\x06proto3',
)


_USERCREATEDV1 = _descriptor.Descriptor(
    name='UserCreatedV1',
    full_name='UserCreatedV1',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='user_id',
            full_name='UserCreatedV1.user_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=16,
    serialized_end=48,
)


_USERUPDATEDV1 = _descriptor.Descriptor(
    name='UserUpdatedV1',
    full_name='UserUpdatedV1',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='user_id',
            full_name='UserUpdatedV1.user_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=50,
    serialized_end=82,
)

DESCRIPTOR.message_types_by_name['UserCreatedV1'] = _USERCREATEDV1
DESCRIPTOR.message_types_by_name['UserUpdatedV1'] = _USERUPDATEDV1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserCreatedV1 = _reflection.GeneratedProtocolMessageType(
    'UserCreatedV1',
    (_message.Message,),
    {
        'DESCRIPTOR': _USERCREATEDV1,
        '__module__': 'schema_pb2'
        # @@protoc_insertion_point(class_scope:UserCreatedV1)
    },
)
_sym_db.RegisterMessage(UserCreatedV1)

UserUpdatedV1 = _reflection.GeneratedProtocolMessageType(
    'UserUpdatedV1',
    (_message.Message,),
    {
        'DESCRIPTOR': _USERUPDATEDV1,
        '__module__': 'schema_pb2'
        # @@protoc_insertion_point(class_scope:UserUpdatedV1)
    },
)
_sym_db.RegisterMessage(UserUpdatedV1)


# @@protoc_insertion_point(module_scope)
